server:
  port: 8090


my:
  name: lee
  age: 28
  address: shenzhen


spring:
  #配置mysql数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sampledb?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
  #配置mongodb数据库链接
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbtest
  main:
    allow-bean-definition-overriding: true
  #配置redis数据库链接
  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 500
  #配置rabbitmq相关信息
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true   #消息发送到交换机确认机制，是否需要回调

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lee.demo.entity